### ISSUE TITLE
create working ROM (base android 11 and if possible newer like Android 12+)

### ISSUE THREAD

**Issue by matu6968** [kelexine/twrp_device_cubot_marlon#1]
Cubot P50 never got security patches for a while (august 2022) and is still stuck at Android 11 so try to make newer Android versions work

**Comment by kelexine** [comment]
First off, am not an official cubot employee, am just doing this as a hubby, I once asked cubot for the kernel source but they bluntly refused, sorry to burst your bubbles but development on this device is not gonna be as progressive as you think cause there's no kernel source code for the device

**Comment by kelexine** [comment]
> Cubot P50 never got security patches for a while (august 2022) and is still stuck at Android 11 so try to make newer Android versions work

You should be mailing cubot asking for security updates or to release the kernel source code.

**Comment by kelexine** [comment]
Also, I'd appreciate it if you only open issues related to TWRP recovery here.

**Comment by matu6968** [comment]
> First off, am not an official cubot employee, am just doing this as a hubby, I once asked cubot for the kernel source but they bluntly refused, sorry to burst your bubbles but development on this device is not gonna be as progressive as you think cause there's no kernel source code for the device 

GPL violation and there are other devices that use Helio P22, notable ones are for [Teracube 2e](https://github.com/techyminati/android_kernel_teracube_mt6762) and [Samsung Galaxy A10s](https://github.com/rsuntk/android_kernel_samsung/a10s-r)
